### ISSUE TITLE
COPY error

### ISSUE THREAD

**Issue by mkazlauskas** [colin-nolan/docker-ffmpeg-rpi#2]
https://github.com/colin-nolan/docker-ffmpeg-rpi/blob/ca66edfe8e8e673797554008e9e31f27be030d57/Dockerfile#L67

Docker gives an error about this line. I believe COPY source globs were removed at some version. 

It appears that it worked well when I changed it to

`COPY --from=ffmpeg-builder /usr/local/src/ffmpeg/ffmpeg.deb /tmp/ffmpeg.deb`

**Comment by colin-nolan** [comment]
Apologies for not seeing your issue earlier - I did not realise that I wasn't subscribed to notifications.

Happily, I did an update on the 24th December (few weeks after you raised this) that removed the glob (perhaps I hit this too!). Therefore this should be fixed. Please let me know if there's still any issues though.
